# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib trizavalr, .registration = TRUE
NULL

#' Computes a block-bootstrap confidence interval for the mean of a
#' numeric vector.
#'
#' @param data A numeric vector of evaluation scores.
#' @param block_size Length of contiguous blocks to resample. Use 1
#'   for an ordinary independent bootstrap; use a larger value when
#'   observations are correlated (e.g. consecutive similar prompts).
#' @param n_resamples Number of bootstrap resamples to perform.
#' @param confidence_level Confidence level, e.g. 0.95 for a 95% CI.
#' @param seed Optional integer seed for reproducible results. Pass
#'   NULL for a non-reproducible, entropy-seeded run.
#' @return A named list with point_estimate, ci_lower, ci_upper,
#'   confidence_level, and n_resamples.
#' @export
block_bootstrap_mean <- function(data, block_size, n_resamples, confidence_level, seed) .Call(wrap__block_bootstrap_mean, data, block_size, n_resamples, confidence_level, seed)

#' Computes Cohen's d and Hedges' g effect size between two groups
#' of scores.
#'
#' @param baseline A numeric vector of baseline scores.
#' @param treatment A numeric vector of treatment/candidate scores.
#' @return A named list with cohens_d, hedges_g, magnitude,
#'   n_baseline, and n_treatment.
#' @export
cohens_d <- function(baseline, treatment) .Call(wrap__cohens_d, baseline, treatment)

#' Applies a multiple-comparisons correction to a vector of p-values.
#'
#' @param p_values A numeric vector of p-values.
#' @param alpha Significance threshold, e.g. 0.05.
#' @param method Either "bonferroni" or "benjamini_hochberg".
#' @return A named list with adjusted_p_values and rejected (a
#'   logical vector).
#' @export
correct_p_values <- function(p_values, alpha, method) .Call(wrap__correct_p_values, p_values, alpha, method)

#' Debiases a single pairwise judge comparison judged twice with
#' positions swapped, to correct for position bias.
#'
#' @param original_order Preference when response A was shown first:
#'   one of "prefers_a", "prefers_b", "tie".
#' @param swapped_order Preference when response B was shown first
#'   (expressed in terms of the same underlying A/B identity).
#' @return A named list with preference and position_bias_detected.
#' @export
debias_pairwise_judgment <- function(original_order, swapped_order) .Call(wrap__debias_pairwise_judgment, original_order, swapped_order)

#' Fits and removes length bias from a batch of LLM-judge scores.
#'
#' @param scores A numeric vector of judge scores.
#' @param lengths A numeric vector of response lengths, same length
#'   and order as `scores`.
#' @return A named list with slope, intercept, correlation, and
#'   adjusted_scores.
#' @export
length_bias_correction <- function(scores, lengths) .Call(wrap__length_bias_correction, scores, lengths)

#' A stateful sequential hypothesis test (mixture SPRT). Feed it
#' observations one at a time via `$update(x)`; stop collecting data
#' as soon as `$update()` returns `rejected = TRUE`.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `new`}{
#'Constructs a new sequential test.
#' \subsection{Arguments}{
#'\describe{
#'\item{`alpha`}{Desired Type I error rate, e.g. 0.05.}
#'\item{`tau`}{Prior standard deviation on the effect size worth detecting.}
#'}}
#'}
#'
#'\subsection{Method `update`}{
#'Feeds one new observation into the test.
#' \subsection{Arguments}{
#'\describe{
#'\item{`x`}{The new observation (e.g. candidate_score - baseline_score).}
#'}}
#' \subsection{return}{
#'A named list with n, likelihood_ratio, and rejected.
#'}
#'}
#'
#'\subsection{Method `current_mean`}{
#'Current running mean of observations fed so far.
#'}
#'
#'\subsection{Method `n`}{
#'Number of observations fed so far.
#'}
#'
RSequentialTest <- new.env(parent = emptyenv())

RSequentialTest$new <- function(alpha, tau) .Call(wrap__RSequentialTest__new, alpha, tau)

RSequentialTest$update <- function(x) .Call(wrap__RSequentialTest__update, self, x)

RSequentialTest$current_mean <- function() .Call(wrap__RSequentialTest__current_mean, self)

RSequentialTest$n <- function() .Call(wrap__RSequentialTest__n, self)

#' @rdname RSequentialTest
#' @usage NULL
#' @export
`$.RSequentialTest` <- function (self, name) { func <- RSequentialTest[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RSequentialTest` <- `$.RSequentialTest`

# nolint end
